### ISSUE TITLE
[Question] Nao Visuals

### ISSUE THREAD

**Issue by louislelay** [robot-descriptions/awesome-robot-descriptions#7]
Hi, thank you for this great repository—it's been really helpful!

I noticed there's a dash ("-") for the Nao visuals. I was initially searching for its URDF or MJCF file for a project, but when I came across this, I wondered if there might be an issue or limitation with the visuals. Could you clarify?

Thanks in advance!

**Comment by stephane-caron** [comment]
Sure thing. That dash is actually a link you can click, as depicted by the thin blue underline:

![image](https://github.com/user-attachments/assets/7214ff0f-5641-4d50-972d-f3d6c8da4e94)

The link goes to the [nao_meshes](https://github.com/ros-naoqi/nao_meshes) repository, which is separate from the NAO description and requires users to run an installer, then manually click/enter text to accept a license. That license (Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License) is different from the BSD-3-Clause of the description. Also, contrary to the BSD-3-Clause, it is not open source (because of the non-commercial and no-derivatives restrictions). We write ➖ rather than ✔️ to draw attention to this.

**Comment by louislelay** [comment]
Ok perfect, thank you!
